buildscript {
    repositories {
        google() // Ensure this is included
        mavenCentral()
    }
    dependencies {
        // Use the latest version for google-services
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google() // Ensure this is included
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
